### ISSUE TITLE
Trying to extract from old IBM PC/IX diskette image

### ISSUE THREAD

**Issue by ghaerr** [ponchofiesta/bffextract-rs#1]
Hello @ponchofiesta,

Your project looks just like what I needed - a utility to extract files from an AIX backup format disk image. Unfortunately, I know very little about the BFF file format, and don't have an AIX system with which to play with.

I'm trying to extract the files from (any of) the floppy disk images from an old IBM PC/IX v1.0 distribution. When I try it, I just get the following (on macOS):
```
$ ./bffextract -tv disk10.img 
 Mode  UID  GID  Size  Modified  Filename 
```
Any ideas on what might be the issue? I have attached the disk image in case that helps. I took a quick look at the disk image with a hex editor and it seems to have the right magic number (0xEA6B):

<img width="789" alt="Screen Shot 2024-12-20 at 9 00 36 PM" src="https://github.com/user-attachments/assets/6c68d928-0bfa-4cc1-863d-b3210c3f55c6" />

Thank you!
[disk10.img.zip](https://github.com/user-attachments/files/18217129/disk10.img.zip)

**Comment by ponchofiesta** [comment]
Hi @ghaerr ,
I had a look into this file. It looks like this disk image is about 40 years old. I wasn't able to get useful files out of it. Maybe the BFF format from AIX 1.0 differs to much from current AIX versions. Even a recent AIX version wasn't able to extract the disk image. Sorry

**Comment by ghaerr** [comment]
Thanks @ponchofiesta for looking at this. I did manage to get another image of the system (PC/IX) booted which has a header file of the C structures used for the backup/restore format. It's not a big deal but I may try writing a little C extraction program, just for the fun of it. It would seem that IBM's PC/IX used the same magic number(s) but not the same actual structures as AIX.

Thank you!

**Comment by ponchofiesta** [comment]
Interesting. I was not able to find header files for the current backup format. Maybe you can adapt bffextract to get the archives extracted.
